### ISSUE TITLE
special characters not properly stored in dhis2

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectApi#13]
In data elements or tracked entity attributes values
special characters like: á / à / â / ä / é / è ... / ì ... / ò ... / ç ...
are stored in dhis2 as: �
this is likely due to the processing done by the web service
what could we do to avoid that?

**Comment by jturtler** [comment]
If used in payload, they get stored as diamond question mark in DHIS.
If we use DHIS interface (Tracker), it stores and present fine.
It could be the javascript eval done within java.

**Comment by jturtler** [comment]
These special characters do seem to work when I try them on 'Postman'.  (See attached)
Maybe there are some different setting on 'character set'/'encoding'?
From Android App, it could maybe not handle the special coding when sending to web service? 
We can try this when we have our meeting.

**Comment by BRaimbault** [comment]
Could it be that the specific field you tested on did not had any "function" applied to it?
